Add test that objects returned by gevent.iwait are iterators
Right now, this code hangs:

    next(gevent.iwait(greenlets))

This is because the WaitIterator initialization happens when __iter__ is called.
Before initialization, nothing is actually being waited-upon

    ERROR: test_wait_noiter (__main__.TestWaiting)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/vagrant/gevent/src/greentest/greentest/leakcheck.py", line 200, in wrapper
        return _RefCountChecker(self, method)(args, kwargs)
      File "/home/vagrant/gevent/src/greentest/greentest/leakcheck.py", line 184, in __call__
        self._run_test(args, kwargs)
      File "/home/vagrant/gevent/src/greentest/greentest/leakcheck.py", line 109, in _run_test
        self.function(self.testcase, *args, **kwargs)
      File "/home/vagrant/gevent/src/greentest/greentest/errorhandler.py", line 48, in wrapper
        return method(self, *args, **kwargs)
      File "/home/vagrant/gevent/src/greentest/greentest/errorhandler.py", line 35, in wrapper
        return method(self, *args, **kwargs)
      File "/home/vagrant/gevent/src/greentest/greentest/testcase.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "src/greentest/test__wait.py", line 12, in test_wait_noiter
        ready = next(gevent.iwait((sem1, sem2)))
      File "src/gevent/_hub_primitives.py", line 149, in gevent.__hub_primitives._WaitIterator.__next__
        raise
      File "src/gevent/_hub_primitives.py", line 140, in gevent.__hub_primitives._WaitIterator.__next__
        item = self._waiter.get()
      File "src/gevent/_waiter.py", line 192, in gevent.__waiter.MultipleWaiter.get
        Waiter.get(self)
      File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
        return self.hub.switch()
      File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
        def switch(self):
      File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
        def switch(self):
      File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
        return _greenlet_switch(self) # pylint:disable=undefined-variable
      File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
        return PyGreenlet_Switch(self, NULL, NULL)
    LoopExit: This operation would block forever
        Hub: <QuietHub '' at 0x7fc8fce60520 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7fc8fffbe700>
        Handles:
    []