Working on gevent/gevent#546 for CPython only.
Fixes several test failures under 2.7.9, notably test__pywsgi and test__ssl.
There are lots of whitespace differences in the tests due to forking for CPython
<= 2.7.8.

The complete failure list follows.

The ONLY failure in 2.7/test_ssl has this traceback; I'm not sure what the cause is yet:

  ======================================================================
  ERROR: test_protocol_sslv2 (__main__.ThreadedTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test_ssl.py", line 71, in f
      return func(*args, **kwargs)
    File "test_ssl.py", line 1205, in test_protocol_sslv2
      try_protocol_combo(ssl.PROTOCOL_SSLv2, ssl.PROTOCOL_SSLv23, True)
    File "test_ssl.py", line 979, in try_protocol_combo
      chatty=False, connectionchatty=False)
    File "test_ssl.py", line 909, in server_params_test
      s.connect((HOST, server.port))
    File "/gevent/gevent/_sslgte279.py", line 546, in connect
      self._real_connect(addr, False)
    File "/gevent/gevent/_sslgte279.py", line 537, in _real_connect
      self.do_handshake()
    File "/gevent/gevent/_sslgte279.py", line 504, in do_handshake
      return self._sslobj.do_handshake()
  SSLEOFError: EOF occurred in violation of protocol (_ssl.c:581)

  ----------------------------------------------------------------------

3/123 expected failures
 - //bin/python -u -m monkey_test test_ssl.py
 - //bin/python -u test__socket_dns6.py
 - //bin/python -u -m monkey_test --Event test_ssl.py

4/123 unexpected failures
 - //bin/python -u test__all__.py
 - //bin/python -u test_ares_timeout.py
 - //bin/python -u -m monkey_test test_httpservers.py
 - //bin/python -u -m monkey_test --Event test_httpservers.py