expect test_ssl.py to fail
This problems seem to have nothing to do with gevent:
SSLError: [Errno 1] _ssl.c:504: error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed