cython fix for setup.py with virtualenv
It can happen that the cython executable is not in the $PATH environment variable. So we need to check if it's available in the python executable path, else we fallback to simply call 'cython'.

Exception:
Running cython -o gevent.core.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && !defined(_WIN32)
sh: 1: cython: not found
Traceback (most recent call last):
  File "util/cythonpp.py", line 801, in <module>
    process_filename(filename, options.output_file)
  File "util/cythonpp.py", line 85, in process_filename
    output = run_cython(pyx_filename, sourcehash, output_filename, banner, comment)
  File "util/cythonpp.py", line 529, in run_cython
    system(command, comment)
  File "util/cythonpp.py", line 539, in system
    raise AssertionError('%r failed with code %s' % (command, result))
AssertionError: 'cython -o gevent.core.c gevent/core.pyx' failed with code 32512
make: *** [gevent/gevent.core.c] Fehler 1