Update libev to 4.20.
This most importantly fixes build issues related to C11 which is used in
for example OS X 10.11 ("El Capitan"):

    libev/ev.c:1029:42: error: '_Noreturn' keyword must precede function declarator
      ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                             ^~~~~~~~~~~~